apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-onelogin-sync
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: app-onelogin-sync
              image: {{REPOSITORY}}:{{TAG}}
              env:
                - name: NODE_ENV
                  value: "production"
                - name: SERVICE
                  value: "app-onelogin-sync"
                - name: ONELOGIN_BASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: secrets-app-onelogin-sync
                      key: onelogin-base-url
                - name: ONELOGIN_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: secrets-app-onelogin-sync
                      key: onelogin-client-id
                - name: ONELOGIN_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: secrets-app-onelogin-sync
                      key: onelogin-client-secret
                - name: APPS_KUALI_BASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: secrets-app-onelogin-sync
                      key: apps-kuali-base-url
                - name: APPS_KUALI_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: secrets-app-onelogin-sync
                      key: apps-kuali-api-key
                - name: APPS_KUALI_ONELOGIN_CATEGORY_ID
                  valueFrom:
                    secretKeyRef:
                      name: secrets-app-onelogin-sync
                      key: apps-kuali-onelogin-category-id
                - name: APPS_KUALI_ONELOGIN_FIELD_ID
                  valueFrom:
                    secretKeyRef:
                      name: secrets-app-onelogin-sync
                      key: apps-kuali-onelogin-field-id
                - name: APPS_SLACK_WEBHOOK
                  valueFrom:
                    secretKeyRef:
                      name: secrets-app-onelogin-sync
                      key: apps-slack-webhook
                - name: LOGGLY_AUTH
                  valueFrom:
                    secretKeyRef:
                      name: loggly-secrets
                      key: loggly-auth
                - name: REGION
                  valueFrom:
                    secretKeyRef:
                      name: not-encrypted-secrets
                      key: region
          restartPolicy: Never
